version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: transcripciones_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=transcripciones_db
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"

#    networks:
#      - shared_network


volumes:
  db_data:
